### ISSUE TITLE
Test the GPT summary with multiple screen readers

### ISSUE THREAD

**Issue by 1Copenut** [1Copenut/moar-accessible-charts#2]
## Description
Once the GPT summary file is in, test with multiple pairings to make sure the SVG container is reading back the summary correctly.

## Task list
- [ ] VoiceOver + Safari (MacOS)
- [ ] VoiceOver + Firefox (MacOS)
- [ ] NVDA + Chrome (Win10)
- [ ] NVDA + Firefox (Win10)
